kind: Deployment            
apiVersion: apps/v1
metadata:
  name: mydeployments
spec:
  selector:
    matchLabels:
      objtype: deployment
  replicas: 2
  template:
    metadata:
      name: testpod8
      labels:
        objtype: deployment
    spec:
     containers:
       - name: c00
         image: ubuntu:20.10
         command: ["/bin/bash", "-c", "while true; do echo Hello-myClass; sleep 5 ; done"]

