kind: HorizontalPodAutoscaler            
apiVersion: autoscaling/v1
metadata:
  name: myhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20

