apiVersion: v1
kind: Pod
metadata:
  name: myvolpod
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo hello-world; sleep 5; done"]
    volumeMounts:
    - name: configvolume
      mountPath: /tmp/
    

  volumes:
  - name: configvolume
    configMap:
      name: volconfigmap
