apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
      version: v1.0.0
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
        version: v1.0.0
    spec:
      containers:
      - name: myapp
        image: jiteshonline/k8s-deployment-strategies:latest
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: v1.0.0

