apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    app: myapp
    version: v2.0.0
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000

