apiVersion: v1
kind: Pod
metadata:
  name: testconfig1
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-myClass; sleep 5; done"]
    env:
    - name: MYENV
      valueFrom:
        configMapKeyRef:
          name: myenvconfigmap
          key: env.conf
    - name: MYTIER
      valueFrom:
        configMapKeyRef:
          name: mytierconfigmap
          key: tier.conf
