kind: Pod                               # Object Type
apiVersion: v1                          # API version
metadata:                               # Set of data which describes the Object
  name: podenv                          # Name of the Object
  labels:
    class: docker
    env: dev
spec:                                   # Data which describes the state of the Object 
  containers:                           # Data which describes the Container details
    - name: c00                         # Name of the Container
      image: ubuntu                     # Base Image which is used to create Container
      command: ["/bin/bash", "-c", "while true; do echo Hello-myClass; sleep 5 ; done"]
      env:
      - name: USER
        value: "Jitesh Agarwal"
      - name: TRINING
        value: "Kubernetes"
