apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
spec:
  limits:
  - default:
      memory: 300Mi
      cpu: 200m
    defaultRequest:
      memory: 100Mi
      cpu: 50m
    type: Container
