apiVersion: v1
kind: Pod
metadata: 
  name: mynginx-pod
  labels: 
    env: prod
    tier: frontend
spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
