kind: Service                                   # Defines to create Service type Object
apiVersion: v1
metadata:
  name: rcservice
spec:
  ports:
    - port: 80                                  # Containers port exposed
      targetPort: 80                            # Pods port
  selector:
    app: nginx
    tier: dev
  type: NodePort


