apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    pvtype: hostpv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data
  persistentVolumeReclaimPolicy: Recycle

