apiVersion: v1
kind: Pod
metadata:
  name : podwithname-secret
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-class; sleep 5; done"]
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username.txt
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password.txt

