apiVersion: v1
kind: Pod
metadata:
  name: testconfig2
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Hello-myClass; sleep 5; done"]
    env:
    - name: MYENV
      valueFrom:
        configMapKeyRef:
          name: evnconfigmap
          key: MYENV
    - name: MYTIER
      valueFrom:
        configMapKeyRef:
          name: evnconfigmap
          key: MYTIER
