apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
        version: v2.0.0
    spec:
      containers:
      - name: myapp
        image: jiteshonline/k8s-deployment-strategies:latest
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: v2.0.0

